### ISSUE TITLE
Resolution Problems

### ISSUE THREAD

**Issue by chrischdi** [Voker57/qmpdclient#23]
Hi,
I'd like to use this player on a netbook with the resolution 1024x768.
I've got the Problem that I'm not able to see and use the complete gui.
At the bottom the Gui gets cutted by the end of the screen and the task bar.

Could this get fixed?

**Comment by Voker57** [comment]
Hi,
QMPClient window can be resized to any required size, cf this screenshot:

![image](https://cloud.githubusercontent.com/assets/22776/7412555/9b290758-ef4c-11e4-9424-253dbc43a671.png)

If your window manager does not resize window to requested size, it's its problem.
